
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 188
#define YY_END_OF_BUFFER 189
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[480] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      189,  188,  121,  164,  152,  108,  109,  163,   81,   82,
      104,  106,  129,  107,  128,  105,  134,  134,  130,  131,
      118,  127,  117,  188,  152,  152,  152,  152,  152,   83,
       84,  110,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,   79,  111,   80,  112,  156,  156,  156,  180,
      177,  180,  176,  188,  162,  161,  160,  187,  184,  183,
      187,  181,  182,  116,  152,   98,  119,   96,   92,   85,
       94,   86,   95,  126,  132,    0,  153,  157,   93,  142,

      134,  149,  139,  135,  101,  114,  115,  123,  113,  102,
      124,  122,  152,  152,  152,  152,  152,  152,  152,   97,
      152,   37,  152,  152,  152,  152,  152,  152,  152,  152,
        9,  152,  152,  152,  152,  152,  152,  152,  152,  152,
       16,  152,   17,   18,  152,  152,  152,  152,  152,   63,
       64,  152,  152,  159,  158,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
       99,  120,  103,  155,  154,  178,  179,  175,  171,  172,
      170,  169,  168,  165,  167,  166,  175,  186,  185,  149,
      150,    0,  151,  157,  132,  145,  141,  149,  132,  148,

      133,  138,  134,   89,   90,  100,  125,   87,  152,  152,
       77,  152,   76,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,   15,   45,  152,
      152,   70,  152,  152,  152,   19,  152,   69,  152,  152,
      152,  152,  152,   55,  152,  152,  152,  152,  152,  152,
      152,  152,   26,  152,   27,  152,  152,  152,  152,  152,
       91,  178,    0,    0,  185,  149,  132,  132,    0,  149,
      150,  145,  146,  144,  140,  150,  147,  137,  136,   88,
      152,   78,  152,  152,  152,  152,  152,  152,  152,   61,

       73,  152,    3,  152,  152,  152,  152,  152,  152,  152,
      152,  152,   10,   11,  152,  152,  152,  152,  152,   62,
      152,  152,  152,   49,  152,  152,   33,  152,   53,  152,
      152,  152,  152,   66,  152,  152,  152,   67,   24,  152,
       31,   57,   28,   68,  152,   29,  152,    0,    0,  150,
      151,  149,  132,  132,    0,  143,    0,  132,    0,  133,
        0,  152,   74,  152,  152,  152,  152,   60,   34,    2,
        4,    5,    6,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,   32,   13,  152,  152,  152,  152,   51,
      152,  152,  152,  152,  152,  152,   22,  152,   25,  152,

       30,   35,    0,  174,  132,  150,  146,    0,  140,  147,
      136,  152,   72,   75,  152,    1,  152,  152,  152,  152,
       71,  152,   41,  152,  152,  152,  152,  152,  152,   47,
      152,  152,  152,  152,  152,   21,   65,   56,   23,  152,
      173,  132,  143,  152,  152,  152,  152,    8,  152,   40,
       12,  152,  152,   44,   14,  152,  152,   50,  152,  152,
       20,   58,   59,   36,    7,  152,   39,  152,   43,  152,
      152,   52,   54,   38,   42,  152,   48,   46,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   27,
       28,   28,   28,   28,   28,   29,   30,   28,   28,   28,
       28,   31,   32,   28,   28,   28,   28,   33,   28,   28,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   28,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   28,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    7,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[499] =
    {   0,
        0,    0,   56,   57,   66,   71,   73,   74,   76,   79,
      702,  703,  679,  703,    0,  678,   78,  703,  703,  703,
      677,   74,  703,   75,   73,   82,   92,  102,  703,  703,
       81,   89,   91,  100,  640,  650,  657,  637,   65,  703,
      703,  672,   91,   82,   84,   86,  101,  107,  650,  645,
      105,  118,  644,  100,  116,  651,  160,  120,  124,  132,
      126,  642,  703,  110,  703,  672,  703,  671,  675,  703,
      703,  622,  703,  183,  703,  703,  703,  703,  703,  703,
      165,  703,  703,  703,    0,  703,  703,  703,  703,  703,
      703,  703,  703,  703,  172,  182,  703,    0,  703,  187,

      194,  210,  646,  218,  661,  703,  703,  703,  703,  170,
      667,  659,  629,  623,  625,  626,  619,  620,  624,  703,
      617,  139,  633,  615,  618,  626,  150,  629,  124,  623,
      608,  614,  608,  605,  164,  167,  611,  606,  603,  617,
        0,  605,  600,    0,  599,  615,  593,  593,  193,    0,
        0,  609,  596,  703,  703,  172,  192,  598,  610,  595,
      600,  595,  192,  188,  592,  589,  596,  208,  585,  598,
      703,  703,  618,  703,  703,    0,  703,  703,  703,  703,
      703,  703,  703,  703,  703,  703,  576,  703,    0,  240,
      227,  242,  244,    0,  246,  256,  249,  258,  262,  268,

      600,  599,  273,  703,  703,  614,  703,  703,  594,  577,
        0,  590,    0,  585,  591,  573,  586,  577,  580,  583,
      576,  585,  580,  581,  565,  236,  581,  238,  579,  579,
      574,  566,  563,  571,  556,  556,  572,    0,    0,  567,
      246,  566,  565,  552,  559,    0,  556,    0,  549,  546,
      544,  139,  552,    0,  540,  542,  555,  540,  555,  539,
      542,  550,    0,  549,    0,  549,  539,  540,  542,  538,
      703,    0,    0,    0,    0,  284,  286,  291,  295,  309,
      297,  301,  313,  319,  323,  325,  327,  548,  547,  703,
      527,    0,  527,  531,  529,  525,  524,  537,  520,    0,

        0,  528,    0,  529,  518,  516,  525,  516,  512,  514,
      519,  517,    0,    0,  511,  277,  513,  521,  514,    0,
      519,  506,  505,    0,  520,  507,    0,  518,    0,  509,
      500,  499,  510,    0,  505,  496,  509,    0,    0,  489,
        0,  506,    0,    0,  504,    0,  504,    0,  480,  331,
      335,  337,  341,  350,  353,  360,  363,  365,  367,  506,
      505,  495,    0,  496,  491,  500,  481,    0,    0,    0,
        0,    0,    0,  486,  489,  486,  479,  490,  482,  466,
      177,  464,  451,    0,  454,  452,  437,  441,  422,    0,
      376,  376,  378,  377,  385,  385,    0,  379,    0,  381,

        0,    0,    0,  703,  369,  372,  377,  379,  382,  391,
      385,  370,    0,    0,  380,    0,  361,  379,  359,  363,
        0,  363,    0,  346,  345,  335,  310,  304,  321,    0,
      323,  298,  304,  307,  286,    0,    0,    0,    0,  294,
      703,  394,  396,  274,  263,  267,  256,    0,  263,    0,
        0,  245,  234,    0,    0,  220,  228,    0,  198,  172,
        0,    0,    0,    0,    0,  145,    0,   75,    0,   48,
       51,    0,    0,    0,    0,   13,    0,    0,  703,  434,
      442,  450,  458,  464,  467,  475,  483,  488,  492,  496,
      504,  509,  513,  515,  517,  521,  523,  527

    } ;

static const flex_int16_t yy_def[499] =
    {   0,
      479,    1,  480,  480,  481,  481,  482,  482,  483,  483,
      479,  479,  479,  479,  484,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  484,  484,  484,  484,  484,  479,
      479,  479,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  485,  479,  486,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  484,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  487,  479,  479,

      479,  479,  488,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  484,  484,  484,  484,  484,  484,  484,  479,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  479,  479,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      479,  479,  479,  479,  479,  489,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  490,  479,  491,  479,
      479,  479,  479,  487,  479,  479,  479,  479,  479,  479,

      488,  492,  479,  479,  479,  479,  479,  479,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      479,  489,  493,  494,  491,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  495,  492,  479,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  496,  494,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  495,
      497,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,

      484,  484,  498,  479,  479,  479,  479,  479,  479,  479,
      497,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      479,  479,  479,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,    0,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479

    } ;

static const flex_int16_t yy_nxt[770] =
    {   0,
       12,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   15,   15,   35,   15,   36,   37,
       38,   39,   15,   40,   12,   41,   42,   15,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   15,   52,   53,
       54,   55,   56,   15,   57,   58,   59,   15,   60,   61,
       15,   62,   63,   64,   65,   66,   68,   68,  478,   71,
       72,   69,   69,   73,   71,   72,   76,   76,   73,   79,
       77,   77,   79,   80,   87,   90,   80,   94,   92,   95,
       95,   81,   97,  477,   81,   91,   93,   98,   96,   88,

       74,  105,  106,   99,  476,   74,  100,  117,  101,  101,
      107,  108,  109,  110,  111,   96,  100,  102,  101,  101,
      124,  118,  127,  112,  103,  475,  119,  102,  130,  104,
      121,  171,  128,  125,  102,  129,  126,  131,   82,  104,
       83,   82,  148,   83,  102,  136,  122,  132,  141,  133,
      123,  134,  103,  137,  142,  143,  145,  149,  138,  150,
      144,  135,  157,  154,  146,  158,  151,  155,  152,  163,
      166,  168,  169,  172,  226,  188,  159,  160,  164,  161,
      189,  162,  227,  167,  331,  165,  179,  180,   95,   95,
      181,  205,  206,  192,  217,  192,  332,  190,  193,  193,

      218,  474,  156,  195,  195,  223,  224,  235,  100,  191,
      101,  101,  196,  473,  190,  236,  233,  182,  424,  102,
      234,  198,  183,  198,  197,  251,  199,  199,  252,  196,
      253,  104,  425,  184,  203,  203,  102,  185,  260,  186,
      187,  247,  248,  278,  278,  262,  261,  200,  254,  263,
      267,  276,  472,  276,  268,  104,  277,  277,  193,  193,
      193,  193,  195,  195,  191,  285,  285,  282,  471,  282,
      470,  280,  283,  283,  199,  199,  309,  200,  199,  199,
      310,  279,  469,  281,  287,  287,  197,  100,  280,  203,
      203,  306,  307,  284,  321,  200,  468,  322,  102,  286,

      277,  277,  277,  277,  467,  200,  466,  278,  278,  465,
      104,  351,  351,  354,  354,  102,  190,  283,  283,  464,
      352,  200,  352,  350,  463,  353,  353,  381,  191,  283,
      283,  382,  279,  190,  281,  356,  356,  462,  284,  285,
      285,  358,  358,  287,  287,  461,  200,  405,  405,  460,
      355,  351,  351,  353,  353,  459,  284,  353,  353,  458,
      357,  457,  286,  456,  359,  455,  354,  354,  350,  407,
      407,  454,  279,  453,  200,  280,  356,  356,  406,  409,
      409,  358,  358,  410,  410,  405,  405,  281,  442,  442,
      355,  452,  280,  407,  407,  443,  443,  408,  409,  409,

      357,  451,  286,  450,  359,  449,  350,  410,  410,  406,
      442,  442,  443,  443,  355,  448,  408,  447,  446,  357,
      445,  444,  361,  440,  439,  438,  437,  436,  359,  435,
      434,  406,  433,  408,   67,   67,   67,   67,   67,   67,
       67,   67,   70,   70,   70,   70,   70,   70,   70,   70,
       75,   75,   75,   75,   75,   75,   75,   75,   78,   78,
       78,   78,   78,   78,   78,   78,   85,   85,   85,   85,
       85,  176,  176,  176,  176,  178,  432,  178,  178,  178,
      178,  178,  178,  194,  431,  194,  194,  194,  194,  194,
      194,  201,  201,  430,  201,  272,  272,  272,  272,  273,

      273,  429,  428,  273,  275,  427,  275,  275,  275,  275,
      275,  275,  289,  289,  426,  289,  348,  348,  349,  349,
      360,  360,  423,  360,  403,  403,  411,  411,  422,  411,
      441,  441,  421,  420,  419,  418,  417,  416,  415,  414,
      413,  412,  361,  288,  404,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  288,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,

      333,  330,  329,  328,  327,  326,  325,  324,  323,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  308,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  202,  288,  274,  271,
      270,  269,  266,  265,  264,  259,  258,  257,  256,  255,
      250,  249,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  232,  231,  230,  229,  228,  225,  222,  221,
      220,  219,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  204,  202,  177,  175,  174,  173,  170,  153,
      147,  140,  139,  120,  116,  115,  114,  113,   89,   86,

       84,  479,   11,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479
    } ;

static const flex_int16_t yy_chk[770] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,  476,    5,
        5,    3,    4,    5,    6,    6,    7,    8,    6,    9,
        7,    8,   10,    9,   17,   22,   10,   25,   24,   25,
       25,    9,   26,  471,   10,   22,   24,   26,   25,   17,

        5,   31,   31,   26,  470,    6,   27,   39,   27,   27,
       32,   32,   33,   33,   34,   25,   28,   27,   28,   28,
       44,   39,   45,   34,   27,  468,   39,   28,   46,   27,
       43,   64,   45,   44,   27,   45,   44,   46,    9,   28,
        9,   10,   54,   10,   28,   48,   43,   46,   51,   47,
       43,   47,   27,   48,   51,   51,   52,   54,   48,   55,
       51,   47,   58,   57,   52,   58,   55,   57,   55,   59,
       60,   61,   61,   64,  129,   81,   58,   58,   59,   58,
       81,   58,  129,   60,  252,   59,   74,   74,   95,   95,
       74,  110,  110,   96,  122,   96,  252,   95,   96,   96,

      122,  466,   57,  100,  100,  127,  127,  136,  101,   95,
      101,  101,  100,  460,   95,  136,  135,   74,  381,  101,
      135,  102,   74,  102,  100,  156,  102,  102,  156,  100,
      157,  101,  381,   74,  104,  104,  101,   74,  163,   74,
       74,  149,  149,  191,  191,  164,  163,  102,  157,  164,
      168,  190,  459,  190,  168,  104,  190,  190,  192,  192,
      193,  193,  195,  195,  191,  197,  197,  196,  457,  196,
      456,  195,  196,  196,  198,  198,  228,  190,  199,  199,
      228,  193,  453,  195,  200,  200,  197,  203,  195,  203,
      203,  226,  226,  196,  241,  198,  452,  241,  203,  199,

      276,  276,  277,  277,  449,  200,  447,  278,  278,  446,
      203,  279,  279,  281,  281,  203,  278,  282,  282,  445,
      280,  276,  280,  277,  444,  280,  280,  316,  278,  283,
      283,  316,  279,  278,  281,  284,  284,  440,  282,  285,
      285,  286,  286,  287,  287,  435,  280,  350,  350,  434,
      283,  351,  351,  352,  352,  433,  284,  353,  353,  432,
      285,  431,  286,  429,  287,  428,  354,  354,  350,  355,
      355,  427,  351,  426,  352,  354,  356,  356,  353,  357,
      357,  358,  358,  359,  359,  405,  405,  354,  406,  406,
      355,  425,  354,  407,  407,  408,  408,  356,  409,  409,

      357,  424,  358,  422,  359,  420,  405,  410,  410,  406,
      442,  442,  443,  443,  407,  419,  408,  418,  417,  409,
      415,  412,  411,  400,  398,  396,  395,  394,  410,  393,
      392,  442,  391,  443,  480,  480,  480,  480,  480,  480,
      480,  480,  481,  481,  481,  481,  481,  481,  481,  481,
      482,  482,  482,  482,  482,  482,  482,  482,  483,  483,
      483,  483,  483,  483,  483,  483,  484,  484,  484,  484,
      484,  485,  485,  485,  485,  486,  389,  486,  486,  486,
      486,  486,  486,  487,  388,  487,  487,  487,  487,  487,
      487,  488,  488,  387,  488,  489,  489,  489,  489,  490,

      490,  386,  385,  490,  491,  383,  491,  491,  491,  491,
      491,  491,  492,  492,  382,  492,  493,  493,  494,  494,
      495,  495,  380,  495,  496,  496,  497,  497,  379,  497,
      498,  498,  378,  377,  376,  375,  374,  367,  366,  365,
      364,  362,  361,  360,  349,  347,  345,  342,  340,  337,
      336,  335,  333,  332,  331,  330,  328,  326,  325,  323,
      322,  321,  319,  318,  317,  315,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  302,  299,  298,  297,  296,
      295,  294,  293,  291,  289,  288,  270,  269,  268,  267,
      266,  264,  262,  261,  260,  259,  258,  257,  256,  255,

      253,  251,  250,  249,  247,  245,  244,  243,  242,  240,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  227,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  212,  210,  209,  206,  202,  201,  187,  173,
      170,  169,  167,  166,  165,  162,  161,  160,  159,  158,
      153,  152,  148,  147,  146,  145,  143,  142,  140,  139,
      138,  137,  134,  133,  132,  131,  130,  128,  126,  125,
      124,  123,  121,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  105,  103,   72,   69,   68,   66,   62,   56,
       53,   50,   49,   42,   38,   37,   36,   35,   21,   16,

       13,   11,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[189] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
#line 2 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
#include <stdio.h>
#include <string.h>
#line 810 "lex.yy.c"

#line 30 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
    void deleteUnderscores(char* src, char* result);
#line 814 "lex.yy.c"
#line 34 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
    char tmp[1000] = "";
#line 817 "lex.yy.c"
#line 38 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
    #define MAX_STRING_LENGTH 200
    static char stringStack[MAX_STRING_LENGTH];
    static int stringStackTop = -1;

    static void pushStringChar(char c) {
        if (stringStackTop < MAX_STRING_LENGTH - 1)
            stringStack[++stringStackTop] = c;
    }

    static char popStringChar() {
        if (stringStackTop >= 0)
            return stringStack[stringStackTop--];
        return 0;
    }

    static char peekStringChar() {
        if (stringStackTop >= 0)
            return stringStack[stringStackTop];
        return 0;
    }
#line 839 "lex.yy.c"
#line 840 "lex.yy.c"

#define INITIAL 0
#define MULTILINE_COMMENT_STATE 1
#define STRING_STATE 2
#define RAW_STRING_STATE 3
#define INTERPOLATION_STATE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 60 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"



#line 1075 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 480 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 479 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("boolean_literal: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("boolean_literal: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("null_literal: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 98 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("builtin_type: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 125 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 143 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 151 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("curly_bracket_open: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 152 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("curly_bracket_close: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 153 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("round_bracket_open: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 154 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("round_bracket_close: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 155 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("square_bracket_open: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 156 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("square_bracket_close: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 158 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("increment: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 159 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("decrement: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 161 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("null_coalescing_assignment: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 162 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("unsigned_shift_right_assignment: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("shift_left_assignment: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("shift_right_assignment: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("integer_division_assignment: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 166 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("multiplication_assignment: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 167 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("division_assignment: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("addition_assignment: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 169 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("subtraction_assignment: %s\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_and_assignment: %s\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_xor_assignment: %s\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 172 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("remainder_assignment: %s\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 173 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_or_assignment: %s\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 175 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("unsigned_shift_right: %s\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 176 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("shift_left: %s\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 177 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("shift_right: %s\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 179 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("integer_division: %s\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 180 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("multiplication: %s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 181 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("division: %s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 182 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("addition: %s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 183 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("subtraction: %s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 184 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("remainder: %s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 186 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_and: %s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 187 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_xor: %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 188 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_or: %s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 189 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("bitwise_not: %s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 191 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("greater_equal: %s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 192 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("less_equal: %s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 193 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("equal: %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 194 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("not_equal: %s\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 195 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("greater: %s\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 196 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("less: %s\n", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 198 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("logical_and: %s\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 199 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("logical_or: %s\n", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 200 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("logical_not: %s\n", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 202 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("null_coalescing: %s\n", yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 204 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("function_arrow: %s\n", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 206 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("null_aware_access: %s\n", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 207 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("null_aware_cascade: %s\n", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 208 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("cascade: %s\n", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 210 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("assignment: %s\n", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 212 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("dot: %s\n", yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 213 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("comma: %s\n", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 214 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("colon: %s\n", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 215 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ printf("semicolon: %s\n", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 218 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  double doubleValue = strtod(tmp, NULL);
  printf("double_literal: %f\n", doubleValue); 
  }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 224 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  long decimalValue = strtol(tmp + 2, NULL, 16);
  printf("integer_literal: %ld\n", decimalValue); 
  }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 230 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  printf("integer_literal: %d\n", atoi(tmp)); 
  }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 236 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid integer literal: %s\n", yytext);
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 240 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 244 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 248 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 252 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 256 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 260 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 264 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 268 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 272 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 276 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 280 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 284 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 288 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 292 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 296 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 300 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 305 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{ 
  printf("identifier: %s\n", yytext); 
  }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 310 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{yy_push_state(MULTILINE_COMMENT_STATE); printf("Start of a multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 311 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{yy_push_state(MULTILINE_COMMENT_STATE); printf("Start of a multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 312 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{yy_pop_state(); printf("End of multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 313 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT_STATE):
#line 314 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Error: multi-line comment not closed (line #%d)\n", yylineno); yy_pop_state();}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 316 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("A standard comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 321 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\''); yy_push_state(RAW_STRING_STATE); printf("START of a RAW string with a SINGLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 322 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\"'); yy_push_state(RAW_STRING_STATE); printf("START of a RAW string with a DOUBLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 324 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    if (peekStringChar() == '\'') {
        popStringChar();
        yy_pop_state();
        printf("END of a RAW string with a SINGLE quote (yytext = %s)\n", yytext);
    }
    else {}
}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 332 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    if (peekStringChar() == '"') {
        popStringChar();
        yy_pop_state();
        printf("END of a RAW string with a DOUBLE quote (yytext = %s)\n", yytext);
    }
    else {}
}
	YY_BREAK
case 162:
/* rule 162 can match eol */
YY_RULE_SETUP
#line 340 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(RAW_STRING_STATE):
#line 341 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Error: no end of RAW string in (line #%d)\n", yylineno); yy_pop_state();}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 346 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\''); yy_push_state(STRING_STATE); printf("START of a STRING with a SINGLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 347 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\"'); yy_push_state(STRING_STATE); printf("START of a STRING with a DOUBLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 350 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\n Newline (yytext = %s)\n", yytext); }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 351 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\t Tab (yytext = %s)\n", yytext); }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 352 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\r Carriage return (yytext = %s)\n", yytext); }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 353 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\b Backspace (yytext = %s)\n", yytext); }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 354 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\\\ Backlash (yytext = %s)\n", yytext); }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 355 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\' Single quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 356 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\\" Double quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 357 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\$ Dollar (yytext = %s)\n", yytext); }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 358 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters unicod (yytext = %s)\n", yytext); }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 359 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters unicod extended (yytext = %s)\n", yytext); }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 360 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Control characters \\. escaping (yytext = %s)\n", yytext); }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 362 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    if (peekStringChar() == '\'') {
        popStringChar();
        yy_pop_state();
        printf("END of a STRING with a SINGLE quote (yytext = %s)\n", yytext);
    }
    else {}
}
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 370 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    if (peekStringChar() == '"') {
        popStringChar();
        yy_pop_state();
        printf("END of a STRING with a DOUBLE quote (yytext = %s)\n", yytext);
    }
    else {}
}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 379 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("Simple interpolation (yytext = %s)\n", yytext); }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 380 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\$'); yy_push_state(INTERPOLATION_STATE); printf("START of INTERPOLATION (yytext = %s)\n", yytext); }
	YY_BREAK
case 180:
/* rule 180 can match eol */
YY_RULE_SETUP
#line 382 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 383 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("Error: no end of STRING in (line #%d)\n", yylineno);
    while (peekStringChar() != 0) {
        popStringChar();
    } 
    yy_pop_state(); }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 393 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('{'); printf("Opening curly brace in interpolation\n");}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 394 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    if (peekStringChar() == '{') {
        popStringChar();
        printf("Closing curly brace in interpolation\n");
    }
    else if (peekStringChar() == '\$') {
        popStringChar();
        yy_pop_state();
        printf("END of INTERPOLATION\n");
    }
    else {
        printf("Unexpected } in interpolation");
    }
}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 410 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('\''); yy_push_state(STRING_STATE); printf("START of a STRING with a SINGLE quote in INTERPOLATION (yytext = %s)\n", yytext);}
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 411 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{pushStringChar('"'); yy_push_state(STRING_STATE); printf("START of a STRING with a DOUBLE quote in INTERPOLATION (yytext = %s)\n", yytext);}
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 414 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("A standard comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 415 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{yy_push_state(MULTILINE_COMMENT_STATE); printf("Start of a multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 187:
/* rule 187 can match eol */
YY_RULE_SETUP
#line 417 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{printf("%c", yytext[0]);}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION_STATE):
#line 418 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
{
    printf("Error: no end of INTERPOLATION in (line #%d)\n", yylineno);
    while (peekStringChar() != '"' && peekStringChar() != '\'' && peekStringChar() != 0) {
        popStringChar();
    }
    yy_pop_state();
}
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 426 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"
ECHO;
	YY_BREAK
#line 2197 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 480 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 480 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 479);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 426 "C:\\Users\\Борис\\Desktop\\dart-compiler\\lexer\\flex.l"


//Delete '_'
void deleteUnderscores(char* src, char* result) {
  result[0] = 0;
  int j = 0;

  for (int i = 0; src[i] != '\0'; i++) {
    if (src[i] != '_') {
      result[j] = src[i];
      j++;
    }
  }

  result[j] = '\0';
}

void main( int argc, char** argv )
{
    ++argv, --argc;
    if ( argc > 0 )
        yyin = fopen( argv[0], "r" );
    else
        yyin = stdin;

    yylex();

    if (yyin != stdin)
        fclose(yyin);
}
