
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 186
#define YY_END_OF_BUFFER 187
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[533] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  187,  186,  121,  165,  152,  108,
      109,  164,   81,   82,  104,  106,  129,  107,  128,  105,
      134,  134,  130,  131,  118,  127,  117,  186,  152,  152,
      152,  152,  152,   83,   84,  110,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,   79,  111,   80,  112,
      156,  156,  156,  181,  181,  177,  186,  182,  178,  182,
      162,  160,  163,  161,  185,  121,  165,  152,  108,  109,
      164,   81,   82,  104,  106,  129,  107,  128,  105,  134,

      134,  130,  131,  118,  127,  117,  185,  152,  152,  152,
      152,  152,   83,   84,  110,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  183,  111,  184,  112,  116,
      152,   98,  119,   96,   92,   85,   94,   86,   95,  126,
      132,    0,  153,  157,   93,  142,  134,  149,  139,  135,
      101,  114,  115,  123,  113,  102,  124,  122,  152,  152,
      152,  152,  152,  152,  152,   97,  152,   37,  152,  152,
      152,  152,  152,  152,  152,  152,    9,  152,  152,  152,
      152,  152,  152,  152,  152,  152,   16,  152,   17,   18,

      152,  152,  152,  152,  152,   63,   64,  152,  152,  159,
      158,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,   99,  120,  103,  155,
      154,  179,  180,  176,  172,  173,  171,  170,  169,  166,
      168,  167,  176,  149,  150,    0,  151,  157,  132,  145,
      141,  149,  132,  148,  133,  138,  134,   89,   90,  100,
      125,   87,  152,  152,   77,  152,   76,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,   15,   45,  152,  152,   70,  152,  152,  152,   19,

      152,   69,  152,  152,  152,  152,  152,   55,  152,  152,
      152,  152,  152,  152,  152,  152,   26,  152,   27,  152,
      152,  152,  152,  152,   91,  179,    0,    0,  149,  132,
      132,    0,  149,  150,  145,  146,  144,  140,  150,  147,
      137,  136,   88,  152,   78,  152,  152,  152,  152,  152,
      152,  152,   61,   73,  152,    3,  152,  152,  152,  152,
      152,  152,  152,  152,  152,   10,   11,  152,  152,  152,
      152,  152,   62,  152,  152,  152,   49,  152,  152,   33,
      152,   53,  152,  152,  152,  152,   66,  152,  152,  152,
       67,   24,  152,   31,   57,   28,   68,  152,   29,  152,

        0,    0,  150,  151,  149,  132,  132,    0,  143,    0,
      132,    0,  133,    0,  152,   74,  152,  152,  152,  152,
       60,   34,    2,    4,    5,    6,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,   32,   13,  152,  152,
      152,  152,   51,  152,  152,  152,  152,  152,  152,   22,
      152,   25,  152,   30,   35,    0,  175,  132,  150,  146,
        0,  140,  147,  136,  152,   72,   75,  152,    1,  152,
      152,  152,  152,   71,  152,   41,  152,  152,  152,  152,
      152,  152,   47,  152,  152,  152,  152,  152,   21,   65,
       56,   23,  152,  174,  132,  143,  152,  152,  152,  152,

        8,  152,   40,   12,  152,  152,   44,   14,  152,  152,
       50,  152,  152,   20,   58,   59,   36,    7,  152,   39,
      152,   43,  152,  152,   52,   54,   38,   42,  152,   48,
       46,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   27,
       28,   28,   28,   28,   28,   29,   30,   28,   28,   28,
       28,   31,   32,   28,   28,   28,   28,   33,   28,   28,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   28,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   28,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    7,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[552] =
    {   0,
        0,    0,   56,   57,   66,   70,   65,   72,  854,  853,
      856,  855,  107,    0,  858,  863,  835,  863,    0,  834,
       72,  863,  863,  863,  833,   68,  863,   67,  159,   71,
      163,  169,  863,  863,   62,   63,   69,   73,  796,  806,
      813,  793,  136,  863,  863,  828,  143,  136,  161,  165,
      143,  176,  806,  801,  170,   56,  800,  139,  165,  807,
      221,  176,  184,  192,   52,  798,  863,  168,  863,  828,
      863,  827,  831,  863,  778,  863,  237,  863,  863,  777,
      863,  863,  863,  863,  863,  817,  863,    0,  816,  228,
      863,  863,  863,  815,   84,  863,  226,  236,  236,  242,

      248,  863,  863,  234,  247,  259,  252,  778,  788,  795,
      775,  240,  863,  863,  810,  233,  232,  257,  255,  250,
      261,  788,  783,  268,  275,  782,  247,  272,  789,  322,
      285,  274,  282,  286,  780,  863,  282,  863,  810,  863,
        0,  863,  863,  863,  863,  863,  863,  863,  863,  863,
      323,  336,  863,    0,  863,  334,  341,  356,  787,  345,
      802,  863,  863,  863,  863,  315,  808,  800,  770,  764,
      766,  767,  760,  761,  765,  863,  758,  149,  774,  756,
      759,  767,  319,  770,  276,  764,  749,  755,  749,  746,
      325,  339,  752,  747,  744,  758,    0,  746,  741,    0,

      740,  756,  734,  734,  336,    0,    0,  750,  737,  863,
      863,  333,  204,  739,  751,  736,  741,  736,  334,  333,
      733,  730,  737,  349,  726,  739,  863,  863,  759,  863,
      863,    0,  863,  863,  863,  863,  863,  863,  863,  863,
      863,  863,  717,  385,  383,  387,  389,    0,  391,  398,
      401,  407,  413,  415,  741,  740,  420,  863,  863,  755,
      863,  863,  735,  718,    0,  731,    0,  726,  732,  714,
      727,  718,  721,  724,  717,  726,  721,  722,  706,  357,
      722,  383,  720,  720,  715,  707,  704,  712,  697,  697,
      713,    0,    0,  708,  391,  707,  706,  693,  700,    0,

      697,    0,  690,  687,  685,  191,  693,    0,  681,  683,
      696,  681,  696,  680,  683,  691,    0,  690,    0,  690,
      680,  681,  683,  679,  863,    0,    0,    0,  424,  430,
      438,  432,  455,  442,  448,  457,  460,  465,  467,  470,
      689,  688,  863,  668,    0,  668,  672,  670,  666,  665,
      678,  661,    0,    0,  669,    0,  670,  659,  657,  666,
      657,  653,  655,  660,  658,    0,    0,  652,  406,  654,
      662,  655,    0,  660,  647,  646,    0,  661,  648,    0,
      659,    0,  650,  641,  640,  651,    0,  646,  637,  650,
        0,    0,  630,    0,  647,    0,    0,  645,    0,  645,

        0,  621,  472,  474,  479,  482,  489,  484,  496,  501,
      506,  508,  647,  646,  636,    0,  637,  632,  641,  622,
        0,    0,    0,    0,    0,    0,  627,  630,  627,  620,
      631,  626,  615,  313,  617,  607,    0,  605,  600,  592,
      597,  577,    0,  567,  517,  519,  519,  527,  526,    0,
      520,    0,  522,    0,    0,    0,  863,  511,  513,  518,
      520,  523,  525,  526,  510,    0,    0,  519,    0,  501,
      518,  498,  511,    0,  509,    0,  489,  486,  482,  454,
      449,  466,    0,  465,  432,  427,  428,  394,    0,    0,
        0,    0,  408,  863,  530,  535,  393,  371,  377,  360,

        0,  356,    0,    0,  341,  322,    0,    0,  313,  316,
        0,  289,  297,    0,    0,    0,    0,    0,  258,    0,
      259,    0,  221,   61,    0,    0,    0,    0,   46,    0,
        0,  863,  573,  581,  589,  597,  605,  611,  614,  622,
      630,  635,  639,  643,  648,  652,  654,  656,  660,  662,
      666
    } ;

static const flex_int16_t yy_def[552] =
    {   0,
      532,    1,  533,  533,  534,  534,  535,  535,  536,  536,
      537,  537,  532,   13,  532,  532,  532,  532,  538,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  538,  538,
      538,  538,  538,  532,  532,  532,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  532,  532,  532,  532,
      532,  532,  532,  532,  539,  532,  540,  532,  532,  539,
      532,  532,  532,  532,  532,  532,  532,  538,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,

      532,  532,  532,  532,  532,  532,  532,  538,  538,  538,
      538,  538,  532,  532,  532,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  532,  532,  532,  532,  532,
      538,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  541,  532,  532,  532,  532,  542,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  538,  538,
      538,  538,  538,  538,  538,  532,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  532,
      532,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  532,  532,  532,  532,
      532,  543,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  544,  532,  532,  532,  532,  541,  532,  532,
      532,  532,  532,  532,  542,  545,  532,  532,  532,  532,
      532,  532,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  532,  543,  546,  547,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      548,  545,  532,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      549,  547,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  548,  550,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  551,  532,  532,  532,  532,
      532,  532,  532,  550,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  532,  532,  532,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,    0,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532
    } ;

static const flex_int16_t yy_nxt[930] =
    {   0,
       16,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   19,   19,   39,   19,   40,   41,
       42,   43,   19,   44,   16,   45,   46,   19,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   19,   56,   57,
       58,   59,   60,   19,   61,   62,   63,   19,   64,   65,
       19,   66,   67,   68,   69,   70,   72,   72,   79,   80,
       75,   73,   73,   76,   75,   79,   80,   76,  143,  146,
      148,  153,  161,  162,  163,  164,  154,  167,  149,  147,
      165,  166,  155,  144,  201,  146,  168,  224,  225,   77,

       77,  531,  202,  530,   77,  147,   77,   85,   85,   86,
       87,   88,   89,   90,   91,   92,   93,   94,   95,   96,
       97,   98,   99,  100,  101,  102,  103,  104,  105,  106,
      107,   88,   88,  108,   88,  109,  110,  111,  112,   88,
      113,   85,  114,  115,   88,  116,  117,  118,  119,  120,
      121,  122,  123,  124,   88,  125,  126,  127,  128,  129,
       88,  130,  131,  132,   88,  133,  134,   88,  135,  136,
      137,  138,  139,  150,  180,  151,  151,  156,  173,  157,
      157,  204,  177,  156,  152,  157,  157,  181,  158,  227,
      182,  189,  174,  190,  158,  159,  205,  175,  178,  183,

      160,  152,  179,  191,  271,  158,  160,  186,  206,  184,
      272,  158,  185,  197,  192,  207,  187,  208,  213,  198,
      199,  214,  193,  159,  210,  200,  188,  194,  211,  219,
      222,  228,  215,  216,  143,  217,  384,  218,  220,  148,
      235,  236,  307,  223,  237,  221,  153,  149,  385,  144,
      150,  154,  151,  151,  161,  162,  156,  155,  157,  157,
      308,  152,  156,  212,  157,  157,  167,  158,  163,  164,
      180,  238,  177,  158,  159,  168,  239,  529,  152,  160,
      165,  166,  173,  181,  158,  160,  182,  240,  178,  204,
      158,  241,  179,  242,  243,  183,  174,  186,  189,  192,

      190,  175,  159,  227,  205,  184,  187,  193,  185,  528,
      191,  197,  194,  201,  527,  206,  188,  198,  199,  219,
      222,  202,  207,  200,  208,  210,  280,  213,  220,  211,
      214,  224,  225,  223,  281,  221,  259,  260,  526,  151,
      151,  215,  216,  525,  217,  228,  218,  246,  244,  246,
      249,  249,  247,  247,  477,  156,  524,  157,  157,  250,
      245,  257,  257,  523,  212,  244,  158,  252,  478,  252,
      522,  251,  253,  253,  277,  278,  250,  287,  160,  289,
      314,  288,  160,  158,  301,  302,  305,  290,  315,  306,
      316,  321,  521,  254,  317,  322,  329,  520,  329,  331,

      331,  330,  330,  247,  247,  247,  247,  249,  249,  335,
      519,  335,  359,  360,  336,  336,  333,  338,  338,  518,
      245,  362,  254,  253,  253,  363,  332,  517,  334,  253,
      253,  340,  340,  333,  156,  337,  257,  257,  251,  374,
      330,  330,  375,  516,  254,  158,  330,  330,  404,  404,
      339,  515,  254,  514,  331,  331,  434,  160,  407,  407,
      435,  254,  158,  244,  336,  336,  405,  403,  405,  332,
      513,  406,  406,  336,  336,  245,  409,  409,  512,  334,
      244,  338,  338,  411,  411,  337,  340,  340,  458,  458,
      404,  404,  254,  511,  408,  406,  406,  337,  406,  406,

      460,  460,  410,  510,  339,  407,  407,  412,  509,  403,
      508,  332,  409,  409,  333,  507,  254,  462,  462,  459,
      506,  408,  411,  411,  463,  463,  334,  458,  458,  495,
      495,  333,  505,  461,  460,  460,  496,  496,  410,  462,
      462,  463,  463,  339,  504,  412,  495,  495,  403,  503,
      459,  496,  496,  502,  501,  408,  500,  461,  499,  498,
      410,  497,  412,  414,  493,  492,  491,  459,  490,  489,
      488,  487,  461,   71,   71,   71,   71,   71,   71,   71,
       71,   74,   74,   74,   74,   74,   74,   74,   74,   78,
       78,   78,   78,   78,   78,   78,   78,   81,   81,   81,

       81,   81,   81,   81,   81,   83,   83,   83,   83,   83,
       83,   83,   83,  141,  141,  141,  141,  141,  232,  232,
      232,  232,  234,  486,  234,  234,  234,  234,  234,  234,
      248,  485,  248,  248,  248,  248,  248,  248,  255,  255,
      484,  255,  326,  326,  326,  326,  327,  327,  483,  482,
      327,  342,  342,  481,  342,  401,  401,  402,  402,  413,
      413,  480,  413,  456,  456,  464,  464,  479,  464,  494,
      494,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  414,  341,  457,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,

      441,  440,  439,  438,  437,  436,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  341,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  383,  382,  381,  380,  379,  378,  377,  376,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      361,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  256,  341,  328,
      325,  324,  323,  320,  319,  318,  313,  312,  311,  310,
      309,  304,  303,  300,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  286,  285,  284,  283,  282,  279,  276,
      275,  274,  273,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  258,  256,  229,  226,  209,  203,  196,
      195,  176,  172,  171,  170,  169,  145,  142,  140,  233,
      233,  231,  230,  229,  226,  209,  203,  196,  195,  176,
      172,  171,  170,  169,  145,  142,  140,  532,   84,   84,
       82,   82,   15,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,

      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532
    } ;

static const flex_int16_t yy_chk[930] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    7,    7,
        5,    3,    4,    5,    6,    8,    8,    6,   21,   26,
       28,   30,   35,   35,   36,   36,   30,   38,   28,   26,
       37,   37,   30,   21,   56,   95,   38,   65,   65,    7,

        5,  529,   56,  524,    6,   95,    8,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   29,   48,   29,   29,   31,   43,   31,
       31,   58,   47,   32,   29,   32,   32,   48,   31,   68,
       48,   51,   43,   51,   32,   31,   58,   43,   47,   49,

       31,   29,   47,   51,  178,   31,   32,   50,   59,   49,
      178,   32,   49,   55,   52,   59,   50,   59,   62,   55,
       55,   62,   52,   31,   61,   55,   50,   52,   61,   63,
       64,   68,   62,   62,   90,   62,  306,   62,   63,   97,
       77,   77,  213,   64,   77,   63,   99,   97,  306,   90,
       98,   99,   98,   98,  104,  104,  100,   99,  100,  100,
      213,   98,  101,   61,  101,  101,  107,  100,  105,  105,
      117,   77,  116,  101,  100,  107,   77,  523,   98,  100,
      106,  106,  112,  117,  100,  101,  117,   77,  116,  127,
      101,   77,  116,   77,   77,  118,  112,  119,  120,  121,

      120,  112,  100,  137,  127,  118,  119,  121,  118,  521,
      120,  124,  121,  125,  519,  128,  119,  124,  124,  132,
      133,  125,  128,  124,  128,  130,  185,  131,  132,  130,
      131,  134,  134,  133,  185,  132,  166,  166,  513,  151,
      151,  131,  131,  512,  131,  137,  131,  152,  151,  152,
      156,  156,  152,  152,  434,  157,  510,  157,  157,  156,
      151,  160,  160,  509,  130,  151,  157,  158,  434,  158,
      506,  156,  158,  158,  183,  183,  156,  191,  157,  192,
      219,  191,  160,  157,  205,  205,  212,  192,  219,  212,
      220,  224,  505,  158,  220,  224,  244,  502,  244,  245,

      245,  244,  244,  246,  246,  247,  247,  249,  249,  250,
      500,  250,  280,  280,  250,  250,  249,  251,  251,  499,
      245,  282,  244,  252,  252,  282,  247,  498,  249,  253,
      253,  254,  254,  249,  257,  250,  257,  257,  251,  295,
      329,  329,  295,  497,  252,  257,  330,  330,  332,  332,
      253,  493,  254,  488,  331,  331,  369,  257,  334,  334,
      369,  329,  257,  331,  335,  335,  333,  330,  333,  332,
      487,  333,  333,  336,  336,  331,  337,  337,  486,  334,
      331,  338,  338,  339,  339,  335,  340,  340,  403,  403,
      404,  404,  333,  485,  336,  405,  405,  337,  406,  406,

      408,  408,  338,  484,  339,  407,  407,  340,  482,  403,
      481,  404,  409,  409,  407,  480,  405,  410,  410,  406,
      479,  408,  411,  411,  412,  412,  407,  458,  458,  459,
      459,  407,  478,  409,  460,  460,  461,  461,  410,  462,
      462,  463,  463,  411,  477,  412,  495,  495,  458,  475,
      459,  496,  496,  473,  472,  460,  471,  461,  470,  468,
      462,  465,  463,  464,  453,  451,  449,  495,  448,  447,
      446,  445,  496,  533,  533,  533,  533,  533,  533,  533,
      533,  534,  534,  534,  534,  534,  534,  534,  534,  535,
      535,  535,  535,  535,  535,  535,  535,  536,  536,  536,

      536,  536,  536,  536,  536,  537,  537,  537,  537,  537,
      537,  537,  537,  538,  538,  538,  538,  538,  539,  539,
      539,  539,  540,  444,  540,  540,  540,  540,  540,  540,
      541,  442,  541,  541,  541,  541,  541,  541,  542,  542,
      441,  542,  543,  543,  543,  543,  544,  544,  440,  439,
      544,  545,  545,  438,  545,  546,  546,  547,  547,  548,
      548,  436,  548,  549,  549,  550,  550,  435,  550,  551,
      551,  433,  432,  431,  430,  429,  428,  427,  420,  419,
      418,  417,  415,  414,  413,  402,  400,  398,  395,  393,
      390,  389,  388,  386,  385,  384,  383,  381,  379,  378,

      376,  375,  374,  372,  371,  370,  368,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  355,  352,  351,  350,
      349,  348,  347,  346,  344,  342,  341,  324,  323,  322,
      321,  320,  318,  316,  315,  314,  313,  312,  311,  310,
      309,  307,  305,  304,  303,  301,  299,  298,  297,  296,
      294,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      281,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  266,  264,  263,  260,  256,  255,  243,
      229,  226,  225,  223,  222,  221,  218,  217,  216,  215,
      214,  209,  208,  204,  203,  202,  201,  199,  198,  196,

      195,  194,  193,  190,  189,  188,  187,  186,  184,  182,
      181,  180,  179,  177,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  161,  159,  139,  135,  129,  126,  123,
      122,  115,  111,  110,  109,  108,   94,   89,   86,   80,
       75,   73,   72,   70,   66,   60,   57,   54,   53,   46,
       42,   41,   40,   39,   25,   20,   17,   15,   12,   11,
       10,    9,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,

      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[187] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 2 "flex.l"
#include <stdio.h>
#include <string.h>
#line 865 "lex.yy.c"

#line 32 "flex.l"
    void deleteUnderscores(char* src, char* result);
#line 869 "lex.yy.c"
#line 36 "flex.l"
    char tmp[1000] = "";
#line 872 "lex.yy.c"
#line 40 "flex.l"
    #define MAX_STRING_LENGTH 200
    static char stringStack[MAX_STRING_LENGTH];
    static int stringStackTop = -1;

    static void pushStringChar(char c) {
        if (stringStackTop < MAX_STRING_LENGTH - 1)
            stringStack[++stringStackTop] = c;
    }

    static char popStringChar() {
        if (stringStackTop >= 0)
            return stringStack[stringStackTop--];
        return 0;
    }

    static char peekStringChar() {
        if (stringStackTop >= 0)
            return stringStack[stringStackTop];
        return 0;
    }
#line 894 "lex.yy.c"
#line 895 "lex.yy.c"

#define INITIAL 0
#define MULTILINE_COMMENT_STATE 1
#define STRING_SINGLE_STATE 2
#define STRING_DOUBLE_STATE 3
#define RAW_STRING_SINGLE_STATE 4
#define RAW_STRING_DOUBLE_STATE 5
#define INTERPOLATION_STATE 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "flex.l"



#line 1132 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 533 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 532 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 69 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "flex.l"
{ printf("boolean_literal: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "flex.l"
{ printf("boolean_literal: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "flex.l"
{ printf("null_literal: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 109 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 110 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 111 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 113 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 114 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 115 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 116 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 118 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 119 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 120 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "flex.l"
{ printf("keyword: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 "flex.l"
{ printf("builtin_type: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "flex.l"
{ printf("keyword_contextual: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 140 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 148 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 149 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 150 "flex.l"
{ printf("type: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "flex.l"
{ printf("curly_bracket_open: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "flex.l"
{ printf("curly_bracket_close: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "flex.l"
{ printf("round_bracket_open: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "flex.l"
{ printf("round_bracket_close: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "flex.l"
{ printf("square_bracket_open: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "flex.l"
{ printf("square_bracket_close: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 160 "flex.l"
{ printf("increment: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 161 "flex.l"
{ printf("decrement: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 163 "flex.l"
{ printf("null_coalescing_assignment: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 164 "flex.l"
{ printf("unsigned_shift_right_assignment: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 165 "flex.l"
{ printf("shift_left_assignment: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 166 "flex.l"
{ printf("shift_right_assignment: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 167 "flex.l"
{ printf("integer_division_assignment: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 168 "flex.l"
{ printf("multiplication_assignment: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 169 "flex.l"
{ printf("division_assignment: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 170 "flex.l"
{ printf("addition_assignment: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 171 "flex.l"
{ printf("subtraction_assignment: %s\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 172 "flex.l"
{ printf("bitwise_and_assignment: %s\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "flex.l"
{ printf("bitwise_xor_assignment: %s\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 174 "flex.l"
{ printf("remainder_assignment: %s\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 175 "flex.l"
{ printf("bitwise_or_assignment: %s\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 177 "flex.l"
{ printf("unsigned_shift_right: %s\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 178 "flex.l"
{ printf("shift_left: %s\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 179 "flex.l"
{ printf("shift_right: %s\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 181 "flex.l"
{ printf("integer_division: %s\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 182 "flex.l"
{ printf("multiplication: %s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 183 "flex.l"
{ printf("division: %s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 184 "flex.l"
{ printf("addition: %s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 185 "flex.l"
{ printf("subtraction: %s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 186 "flex.l"
{ printf("remainder: %s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 188 "flex.l"
{ printf("bitwise_and: %s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 189 "flex.l"
{ printf("bitwise_xor: %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 190 "flex.l"
{ printf("bitwise_or: %s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 191 "flex.l"
{ printf("bitwise_not: %s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 193 "flex.l"
{ printf("greater_equal: %s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 194 "flex.l"
{ printf("less_equal: %s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 195 "flex.l"
{ printf("equal: %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 196 "flex.l"
{ printf("not_equal: %s\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 197 "flex.l"
{ printf("greater: %s\n", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 198 "flex.l"
{ printf("less: %s\n", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 200 "flex.l"
{ printf("logical_and: %s\n", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 201 "flex.l"
{ printf("logical_or: %s\n", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 202 "flex.l"
{ printf("logical_not: %s\n", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 204 "flex.l"
{ printf("null_coalescing: %s\n", yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 206 "flex.l"
{ printf("function_arrow: %s\n", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 208 "flex.l"
{ printf("null_aware_access: %s\n", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 209 "flex.l"
{ printf("null_aware_cascade: %s\n", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 210 "flex.l"
{ printf("cascade: %s\n", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 212 "flex.l"
{ printf("assignment: %s\n", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 214 "flex.l"
{ printf("dot: %s\n", yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 215 "flex.l"
{ printf("comma: %s\n", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 216 "flex.l"
{ printf("colon: %s\n", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 217 "flex.l"
{ printf("semicolon: %s\n", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 220 "flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  double doubleValue = strtod(tmp, NULL);
  printf("double_literal: %f\n", doubleValue); 
  }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 226 "flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  long decimalValue = strtol(tmp + 2, NULL, 16);
  printf("integer_literal: %ld\n", decimalValue); 
  }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 232 "flex.l"
{ 
  deleteUnderscores(yytext, tmp);
  printf("integer_literal: %d\n", atoi(tmp)); 
  }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 238 "flex.l"
{
    printf("ERROR: invalid integer literal: %s\n", yytext);
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 242 "flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 246 "flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 250 "flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 254 "flex.l"
{
    printf("ERROR: invalid hexadecimal integer literal: %s\n", yytext);
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 258 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 262 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 266 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 270 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 274 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 278 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 282 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 286 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 290 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 294 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 298 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 302 "flex.l"
{
    printf("ERROR: invalid double literal: %s\n", yytext);
}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 307 "flex.l"
{ 
  printf("identifier: %s\n", yytext); 
  }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 312 "flex.l"
{yy_push_state(MULTILINE_COMMENT_STATE); printf("Start of a multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 313 "flex.l"
{yy_push_state(MULTILINE_COMMENT_STATE); printf("Start of a multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 314 "flex.l"
{yy_pop_state(); printf("End of multi-line comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 315 "flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT_STATE):
#line 316 "flex.l"
{printf("Error: multi-line comment not closed (line #%d)\n", yylineno); yy_pop_state();}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 318 "flex.l"
{printf("A standard comment (yytext = %s)\n", yytext);}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 323 "flex.l"
{pushStringChar('\''); yy_push_state(RAW_STRING_SINGLE_STATE); printf("START of a RAW string with a SINGLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 324 "flex.l"
{pushStringChar('\"'); yy_push_state(RAW_STRING_DOUBLE_STATE); printf("START of a RAW string with a DOUBLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 326 "flex.l"
{
    popStringChar();
    yy_pop_state();
    printf("END of a RAW string with a SINGLE quote (yytext = %s)\n", yytext);
}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 331 "flex.l"
{
    popStringChar();
    yy_pop_state();
    printf("END of a RAW string with a DOUBLE quote (yytext = %s)\n", yytext);
}
	YY_BREAK
case 162:
/* rule 162 can match eol */
YY_RULE_SETUP
#line 336 "flex.l"
{}
	YY_BREAK
case 163:
/* rule 163 can match eol */
YY_RULE_SETUP
#line 337 "flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(RAW_STRING_SINGLE_STATE):
case YY_STATE_EOF(RAW_STRING_DOUBLE_STATE):
#line 339 "flex.l"
{printf("Error: no end of RAW string in (line #%d)\n", yylineno); yy_pop_state();}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 342 "flex.l"
{pushStringChar('\''); yy_push_state(STRING_SINGLE_STATE); printf("START of a STRING with a SINGLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 343 "flex.l"
{pushStringChar('\"'); yy_push_state(STRING_DOUBLE_STATE); printf("START of a STRING with a DOUBLE quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 346 "flex.l"
{printf("Control characters \\n Newline (yytext = %s)\n", yytext); }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 347 "flex.l"
{printf("Control characters \\t Tab (yytext = %s)\n", yytext); }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 348 "flex.l"
{printf("Control characters \\r Carriage return (yytext = %s)\n", yytext); }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 349 "flex.l"
{printf("Control characters \\b Backspace (yytext = %s)\n", yytext); }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 350 "flex.l"
{printf("Control characters \\\\ Backlash (yytext = %s)\n", yytext); }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 351 "flex.l"
{printf("Control characters \\' Single quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 352 "flex.l"
{printf("Control characters \\\" Double quote (yytext = %s)\n", yytext); }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 353 "flex.l"
{printf("Control characters \\$ Dollar (yytext = %s)\n", yytext); }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 354 "flex.l"
{printf("Control characters unicod (yytext = %s)\n", yytext); }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 355 "flex.l"
{printf("Control characters unicod extended (yytext = %s)\n", yytext); }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 356 "flex.l"
{printf("Control characters \\. escaping (yytext = %s)\n", yytext); }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 358 "flex.l"
{
    popStringChar();
    yy_pop_state();
    printf("END of a STRING with a SINGLE quote (yytext = %s)\n", yytext);
}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 363 "flex.l"
{
    popStringChar();
    yy_pop_state();
    printf("END of a STRING with a DOUBLE quote (yytext = %s)\n", yytext);
}
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 369 "flex.l"
{printf("Simple interpolation (yytext = %s)\n", yytext); }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 370 "flex.l"
{pushStringChar('\$'); yy_push_state(INTERPOLATION_STATE); printf("START of INTERPOLATION (yytext = %s)\n", yytext); }
	YY_BREAK
case 181:
/* rule 181 can match eol */
YY_RULE_SETUP
#line 372 "flex.l"
{}
	YY_BREAK
case 182:
/* rule 182 can match eol */
YY_RULE_SETUP
#line 373 "flex.l"
{}
	YY_BREAK
case YY_STATE_EOF(STRING_SINGLE_STATE):
case YY_STATE_EOF(STRING_DOUBLE_STATE):
#line 375 "flex.l"
{
    printf("Error: no end of STRING in (line #%d)\n", yylineno);
    while (peekStringChar() != 0) {
        popStringChar();
    } 
    yy_pop_state(); }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 385 "flex.l"
{pushStringChar('{'); printf("Opening curly brace in interpolation\n");}
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 386 "flex.l"
{
    if (peekStringChar() == '{') {
        popStringChar();
        printf("Closing curly brace in interpolation\n");
    }
    else if (peekStringChar() == '\$') {
        popStringChar();
        yy_pop_state();
        printf("END of INTERPOLATION\n");
    }
    else {
        printf("Unexpected } in interpolation");
    }
}
	YY_BREAK
case 185:
/* rule 185 can match eol */
YY_RULE_SETUP
#line 402 "flex.l"
{printf("%c", yytext[0]);}
	YY_BREAK
case YY_STATE_EOF(INTERPOLATION_STATE):
#line 403 "flex.l"
{
    printf("Error: no end of INTERPOLATION in (line #%d)\n", yylineno);
    while (peekStringChar() != '"' && peekStringChar() != '\'' && peekStringChar() != 0) {
        popStringChar();
    }
    yy_pop_state();
}
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 411 "flex.l"
ECHO;
	YY_BREAK
#line 2236 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 533 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 533 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 532);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 411 "flex.l"


//Delete '_'
void deleteUnderscores(char* src, char* result) {
  result[0] = 0;
  int j = 0;

  for (int i = 0; src[i] != '\0'; i++) {
    if (src[i] != '_') {
      result[j] = src[i];
      j++;
    }
  }

  result[j] = '\0';
}

void main( int argc, char** argv )
{
    ++argv, --argc;
    if ( argc > 0 )
        yyin = fopen( argv[0], "r" );
    else
        yyin = stdin;

    yylex();

    if (yyin != stdin)
        fclose(yyin);
}
