%{
    #include <stdio.h>
%}

/* Литералы */
%token INT_LIT
%token DOUBLE_LIT
%token ID
%token STRING_LIT
%token BOOL_LIT

/**/ Ключевые слова */
%token BREAK_KW CASE_KW CATCH_KW CLASS_KW CONST_KW CONTINUE_KW
%token DEFAULT_KW DO_KW ELSE_KW ENAM_KW EXTENDS_KW FINAL_KW
%token FINALLY_KW FOR_KW IF_KW IN_KW IS_KW ISN_KW NEW_KW RETHROW_KW
%token RETURN_KW SUPER_KW SWITCH_KW THIS_KW THROW_KW TRY_KW
%token VAR_KW VOID_KW WHILE_KW TRUE_KW FALSE_KW NULL_KW
%token ABSTRACT_KW AS_KW EXPORT_KW FACTORY_KW GET_KW
%token IMPORT_KW REQUIRED_KW SET_KW STATIC_KW WHEN_KW LIST_KW

/* Типы */
%token VOID_TYPE

%token EQ NEQ LEQ GEQ /* == != <= >= */
%token LOG_AND LOG_OR /* && || */
%token INC DEC /* ++ -- */
%token INTDIV COSCADE /* ~/ .. */

%token ADD_ASSIGN SUB_ASSIGN MUL_ASSIGN /* += -= *= */
%token DIV_ASSIGN MOD_ASSIGN INTDIV_ASSIGN /* /= %= ~/= */


/* приоритеты */
%right '=' ADD_ASSIGN SUB_ASSIGN MUL_ASSIGN DIV_ASSIGN MOD_ASSIGN INTDIV_ASSIGN
%left LOG_OR
%left LOG_AND
%nonassoc EQ NEQ
%nonassoc AS_KW IS_KW ISN_KW LEQ GEQ '<' '>'
%left '+' '-'
%left '*' '/' '%' INTDIV
%nonassoc INC DEC '.' '!' '['
%nonassoc '('


%start program

%union {
    int Int;
    double Dbl;
    char* Str;
}

%%


expr:
      primary
    | expr INC /* x++ */
    | expr DEC /* x-- */
    | expr '.' ID /* x.y */
    | expr '(' expr_list_empty ')' /* x(...) */
    | expr '.' ID '(' expr_list_empty ')' /* x.y(...) */
    | expr '[' expr ']' /* x[i] */
    | INC expr /*++x*/
    | DEC expr /*--x*/
    | '-' expr /*-x*/
    | '!' expr /*!x*/
    | '~' expr /*~x*/
    | expr '*' expr /* x*y */
    | expr '/' expr /* x/y */
    | expr '%' expr /* x%y */
    | expr INTDIV expr /* x~/y */
    | expr '+' expr /* x+y */
    | expr '-' expr /* x-y */
    | expr '<' expr /* x<y */
    | expr '>' expr /* x>y */
    | expr LEQ expr /* x<=y */
    | expr GEQ expr /* x>=y */
    | expr IS_KW ID /* x is y */
    | expr AS_KW ID /* x as y */
    | expr ISN_KW ID /* x is! */
    | expr EQ expr /* x==y */
    | expr NEQ expr /* x!=y */
    | expr LOG_AND expr /* x&&y */
    | expr LOG_OR expr /* x||y */
    | expr '?' expr ':' expr
;


primary: /*базовые литералы*/
      INT_LIT
    | DOUBLE_LIT
    | ID
    | STRING_LIT
    | BOOL_LIT
    | NULL_KW
    | SUPER_KW
    | THIS_KW
    | '(' expr ')'
    | '[' expr_list_empty ']'
;


expr_list_empty:
      expr_list
    | /*empty*/
;


expr_list:
      expr
    | expr_list ',' expr
;

%%