%{
    #include <stdio.h>
%}

/* Литералы */
%token INT_LIT
%token DOUBLE_LIT
%token ID
%token STRING_LIT

/**/ Ключевые слова */
%token BREAK_KW CASE_KW CATCH_KW CLASS_KW CONST_KW CONTINUE_KW
%token DEFAULT_KW DO_KW ELSE_KW ENAM_KW EXTENDS_KW FINAL_KW
%token FINALLY_KW FOR_KW IF_KW IN_KW IS_KW ISN_KW NEW_KW RETHROW_KW
%token RETURN_KW SUPER_KW SWITCH_KW THIS_KW THROW_KW TRY_KW
%token VAR_KW VOID_KW WHILE_KW TRUE_KW FALSE_KW NULL_KW
%token ABSTRACT_KW AS_KW EXPORT_KW FACTORY_KW GET_KW
%token IMPORT_KW REQUIRED_KW SET_KW STATIC_KW WHEN_KW LIST_KW

/* Типы */
%token VOID_TYPE

%token EQ NEQ LEQ GEQ /* == != <= >= */
%token LOG_AND LOG_OR /* && || */
%token INC DEC /* ++ -- */
%token INTDIV COSCADE /* ~/ .. */

%token ADD_ASSIGN SUB_ASSIGN MUL_ASSIGN /* += -= *= */
%token DIV_ASSIGN MOD_ASSIGN INTDIV_ASSIGN /* /= %= ~/= */


/* приоритеты */
%right '=' ADD_ASSIGN SUB_ASSIGN MUL_ASSIGN DIV_ASSIGN MOD_ASSIGN INTDIV_ASSIGN
%left LOG_OR
%left LOG_AND
%nonassoc EQ NEQ
%nonassoc AS_KW IS_KW ISN_KW LEQ GEQ '<' '>'
%left '+' '-'
%left '*' '/' '%' INTDIV
%nonassoc INC DEC '.' '!' '['
%nonassoc '('


%start program

%union {
    int Int;
    double Dbl;
    char* Str;
}

%%


expr:
      conditional
;

 
conditional: /* тернарный оператор */
      logical_or
    | logical_or '?' expr ':' expr
;


logical_or: /* логическое или */
      logical_and
    | logical_or LOG_OR logical_and /* x||y */
;


logical_and: /* логическое и */
      equality
    | logical_and LOG_AND equality /* x&&y */
;


equality: /* равенство */
      relational
    | equality EQ relational /* x==y */
    | equality NEQ relational /* x!=y */
;


relational: /* сравнение */
      additive
    | relational '<' additive /* x<y */
    | relational '>' additive /* x>y */
    | relational LEQ additive /* x<=y */
    | relational GEQ additive /* x>=y */
    | relational IS_KW type /* x is y */
    | relational AS_KW type /* x as y */
    | relational ISN_KW type /* x is! */
;


additive: /* сложение вычитание */
      multiplicative
    | additive '+' multiplicative /* x+y */
    | additive '-' multiplicative /* x-y */
;


multiplicative:
      prefix
    | multiplicative '*' prefix /* x*y */
    | multiplicative '/' prefix /* x/y */
    | multiplicative '%' prefix /* x%y */
    | multiplicative INTDIV prefix /* x~/y */
;


prefix: /*опрерации перед операндом*/
      postfix
    | INC prefix /*++x*/
    | DEC prefix /*--x*/
    | '-' prefix /*-x*/
    | '!' prefix /*!x*/
    | '~' prefix /*~x*/
;


postfix: /*операции полсле операнда*/
      primary
    | postfix INC /* x++ */
    | postfix DEC /* x-- */
    | postfix '.' ID /* x.y */
    | postfix arguments /* x(...) */
    | postfix '.' ID arguments /* x.y(...) */
    | postfix '[' expr ']' /* x[i] */
;


primary: /*базовые литералы*/
      INT_LIT
    | DOUBLE_LIT
    | ID
    | STRING_LIT
    | TRUE_KW
    | FALSE_KW
    | NULL_KW
    | SUPER_KW
    | THIS_KW
    | '(' expr ')'
    | '[' expr_list_empty ']'
;


expr:
     
;


arguments: /*аргументы*/
      '(' expr_list_empty ')'
;


expr_list_empty:
      expr_list
    | /*empty*/
;


expr_list:
      expr
    | expr_list ',' expr
;


type: /*типы*/
      NUM_TYPE
    | INT_TYPE
    | DOUBLE_TYPE
    | BOOL_TYPE
    | STRING_TYPE
    | ID
;

%%